LunarLander-v3:
    n_envs: 20
    n_timesteps: !!float 200000
    policy: 'MlpPolicy'
    n_steps: 1
    learning_rate: 0.002
    ent_coef: 0.000005
    gae_lambda: 0.0
    max_grad_norm: !!float 1e10
